sonar.projectKey=propertyquest-app
sonar.projectName=propertyquest-app
sonar.projectVersion=1.0.0

sonar.sources=properQuestServer/src,PropertyQuestClient/src
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**
sonar.sourceEncoding=UTF-8